name: Shared Continuous Integration

on:
  workflow_call:

permissions: {}

jobs:
  build-ci:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@f8255a6a37eb141fa331527f5aed9b9e1d598c77 # 0.38.0
    permissions:
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      oci-registry: ${{ vars.OCI_REGISTRY }}
      sign: false
      images: |
        [
          {
            "name": "backend-ci",
            "context": ".",
            "dockerfile": "./docker/backend/Dockerfile",
            "target": "ci",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "frontend-ci",
            "context": ".",
            "dockerfile": "./docker/frontend/Dockerfile",
            "target": "ci",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "live-data-generator-ci",
            "context": ".",
            "dockerfile": "./docker/live-data-generator/Dockerfile",
            "target": "ci",
            "platforms": ["linux/amd64"]
          }
        ]

  continuous-integration:
    name: Continuous Integration - ${{ matrix.application }}
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@df348077afa4e79725151d50606e9dc63f86dcb6 # ratchet:hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@0.24.4
    needs: build-ci
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      security-events: write
    secrets:
      container-password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: backend-ci
            image: backend-ci
            path: ./applications/monitoring-workspace/backend
          - application: frontend-ci
            image: frontend-ci
            path: ./applications/monitoring-workspace/frontend
          - application: live-data-generator-ci
            image: live-data-generator-ci
            path: ./applications/live-data-generator
    with:
      working-directory: /usr/src/app
      container: |
        {
          "image": ${{ toJSON(fromJSON(needs.build-ci.outputs.built-images)[matrix.image].images[0]) }},
          "credentials": {
            "username": ${{ toJson(github.repository_owner) }}
          },
          "pathMapping": {
            "/usr/src/app": "${{ matrix.path }}"
          }
        }

  build:
    needs: continuous-integration
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@f8255a6a37eb141fa331527f5aed9b9e1d598c77 # 0.38.0
    permissions:
      contents: read
      id-token: write
      issues: read
      packages: write
      pull-requests: read
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      images: |
        [
          {
            "name": "backend",
            "context": ".",
            "dockerfile": "./docker/backend/Dockerfile",
            "target": "prod",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "frontend",
            "context": ".",
            "dockerfile": "./docker/frontend/Dockerfile",
            "target": "prod",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "live-data-generator",
            "context": ".",
            "dockerfile": "./docker/live-data-generator/Dockerfile",
            "target": "prod",
            "platforms": ["linux/amd64"]
          }
        ]

  tests-charts:
    name: Tests - Charts
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          persist-credentials: false

      - name: Test helm charts
        uses: hoverkraft-tech/ci-github-container/actions/helm/test-chart@f8255a6a37eb141fa331527f5aed9b9e1d598c77 # 0.38.0
        with:
          oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
          helm-set: |-
            backend.image=${{ fromJSON(needs.build.outputs.built-images).backend.images[0] }}
            frontend.image=${{ fromJSON(needs.build.outputs.built-images).frontend.images[0] }}
            live-data-generator.api.image=${{ fromJSON(needs.build.outputs.built-images)['live-data-generator'].images[0] }}
            live-data-generator.ui.image=${{ fromJSON(needs.build.outputs.built-images)['live-data-generator'].images[0] }}
            global.imagePullSecrets[0].name=regcred
